coverage:
  status:
    project:
      default:
        target: 25%
        threshold: 0%
        if_ci_failed: error
        informational: false
        only_pulls: true
    patch:
      target: 25%