coverage:
  status:
    project:
      default:
        target: 25%
        threshold: 0%
        if_ci_failed: error
        informational: false
        only_pulls: true
    patch:
      default:
        target: 25%
comment:                  # this is a top-level key
  layout: "diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [true :: must have a base report to post]
  require_head: true       # [true :: must have a head report to post]
flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: auto