package(default_visibility = ["//visibility:public"])

java_library(
    name = "example",
    srcs = glob([
        "*.java",
    ]),
)

#java_library(
#    name = "Adder",
#    srcs = [
#        "Adder.java",
#    ],
#)
#
#java_library(
#    name = "MathFunctions",
#    srcs = [
#        "Divider.java",
#        "Multiplier.java",
#        "Subtractor.java",
#        ":Adder",
#    ],
#)
