steps:
  - command:
      - 'cat .buildkite/integration.yml'
      - "bazel query \"//...\" | grep \"push-image-integration\\$\""
      - "./buildkite_scripts/push_images_integration.sh"
    label: "Push images - Integration"
    agents:
      queue: "default"
    cancel_on_build_failing: true
  - command:
      - "echo Running integration tests..."
      - "sleep 5"
    key: "integration-tests"
    cancel_on_build_failing: true
  - trigger: "push-to-prod"
    label: "Push images - Prod"
    depends_on: "integration-tests"
    async: true
    cancel_on_build_failing: true