steps:
  - command:
#      - 'cat .buildkite/integration-tests.yml'
      - "echo Running integration tests..."
#      - "sleep 1"
    key: "integration-tests"
    cancel_on_build_failing: true
    label: "Execute L2 Tests"
  - trigger: "push-to-prod"
    label: "Trigger: Push images to Prod"
    depends_on: "integration-tests"
    async: true