steps:
  - command:
#      - "git diff --name-only $BUILDKITE_COMMIT..$BUILDKITE_PULL_REQUEST_BASE_BRANCH"
      - "cat .buildkite/pipeline.yml"
      - "bazel coverage --combined_report=lcov --instrumentation_filter=\"-@com_google_protobuf,-@io_grpc_grpc_java,-.*/test/*\" --test_tag_filters=L0 --test_timeout=5 --test_output=errors //..."
      - "codecov -F L0 -t d60cc17b-8753-4639-9d85-79dd58f645a1 -f bazel-out/_coverage/_coverage_report.dat"
      - "./buildkite_scripts/find_and_upload_test_xml_files.sh L0"
    label: "L0"
    agents:
      queue: "default"
    cancel_on_build_failing: true
  - command:
      - "bazel coverage --combined_report=lcov --instrumentation_filter=\"-@com_google_protobuf,-@io_grpc_grpc_java,-.*/test/*\" --test_tag_filters=L1 --test_timeout=60 --test_output=errors //..."
      - "codecov -F L1 -t d60cc17b-8753-4639-9d85-79dd58f645a1 -f bazel-out/_coverage/_coverage_report.dat"
      - "./buildkite_scripts/find_and_upload_test_xml_files.sh L1"
    label: "L1"
    agents:
      queue: "default"
    cancel_on_build_failing: true
  - command:
      - "bazel query \"//...\" | grep \"push-image\\b\""
      - "./buildkite_scripts/push_images.sh"
    label: "Push images"
    agents:
      queue: "default"
    cancel_on_build_failing: true
  - trigger: "push-to-integration"
    async: true
