package(default_visibility = ["//visibility:public"])

java_library(
    name = "CalculatorLibrary",
    srcs = glob([
        "*.java",
    ]),
    deps = [
        "//math-functions-lib/src/main/java/org/example",
    ],
)
